import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from './page.module.css';
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <div className={styles.navbar}>
          <Link href="/" className={styles.link}>
            Rain
          </Link>
          <Link href="/sites" className={styles.link}>
            Sites
          </Link>
          <Link href="/rainfalldata" className={styles.link}>
            Data
          </Link>
          <Link href="/reports" className={styles.link}>
            Reports
          </Link>
      </div>

        {children}

      </body>
    </html>
  );
}
